apiVersion: v1
kind: Namespace
metadata:
  name: weathergpt
  labels:
    name: weathergpt
    app: weathergpt
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weathergpt
  namespace: weathergpt
  labels:
    app: weathergpt
